sudo: required
services:
  - docker

before_install:
  - docker build -t jwj0831/my-docker-react2 -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jwj0831/my-docker-react2 npm run test -- --coverage

after_success:
  - docker build -t jwj0831/multi-client ./client
  - docker build -t jwj0831/multi-nginx ./nginx
  - docker build -t jwj0831/multi-server ./server
  - docker build -t jwj0831/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jwj0831/multi-client
  - docker push jwj0831/multi-nginx
  - docker push jwj0831/multi-server
  - docker push jwj0831/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "ap-northeast-2"
#   app: "MultiCLient"
#   env: "MultiClient-env"
#   bucket_name: "elasticbeanstalk-ap-northeast-2-439361245083"
#   bucket_path: "docker-multi"
#   on:
#     branch: master
#   access_key_id:
#     secure: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY